spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.104/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  redis:
    host: 192.168.1.104
    prot: 6379
server:
  context-path: /sell
wechat:
  openAppId:
  openAppSecret:
  mpAppId:  wxfd959f83532aa72b
  mpAppSecret:  6f5b8573e922fd9c386789ef3be00755
  mchId:
  mchKey:
  keyPath:
  notifyUrl:
  templateId:
    orderStatus: JwXQEFHrtDHuREtk2niUj6uXPHYA783QNxWdAclfAN8
projectUrl:
  wechatMpAuthorize: http://1fann.natapp1.cc
  wechatOpenAuthorize: http://1fann.natapp1.cc
  sell: http://1fann.natapp1.cc
